### ISSUE TITLE
java.lang.OutOfMemoryError: PermGen space

### ISSUE THREAD

**Issue by TamakiSakura** [bcit-ci/netbeans-plugin#47]
It is very easy to get this error after using Netbeans with our plugin (version in the developer branch) for a very short time (~less than 2 minutes).
I am not sure if it is just because I have a bad computer but it at least have 4GB of memory. And Netbeans is going to use ~700MB only with one PHP project open.
Does anyone have the same problem here? Where could the problem come from?

**Comment by jim-parry** [comment]
This looks like a problem caused by constant loading/unloading of Java classes inside NB.
You can alleviate it by adding some settings to your NB startup config, NETBEANS/etc/netbeans.conf

Look for "netbeans_default_options="
Add to the list of command-line options specified there...
-J-XX:MaxPermSize=256M -J-XX:+CMSClassUnloadingEnabled -J-XX:+CMSPermGenSweepingEnabled

**Comment by TamakiSakura** [comment]
The options works, but the file should be modified is not netbeans.conf, which will only affect the running option for the current netbeans running. To affect the netbeans that is run through the Run Project command, we need to modified the NETBEANS/harness/run.xml. 

I am currently making the Ln172 of this file looks like:
property name="run.args.ide" value="-J-XX:MaxPermSize=256M -J-XX:+CMSClassUnloadingEnabled -J-XX:+CMSPermGenSweepingEnabled"

Not sure If this may cause some other problem.
